apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - helm.yaml
configMapGenerator:
  - name: ingress-nginx-base-values
    files:
      - values.yaml
configurations:
  - kustomizeconfig.yaml