apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-dns
resources:
  - ../../base
configMapGenerator:
  - name: external-dns-overlay-values
    files:
      - values.yaml