apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ingress-nginx
resources:
  - ../../base
configMapGenerator:
  - name: ingress-nginx-overlay-values
    files:
      - values.yaml=values.yaml